[versions]
kotlin = "2.2.21"
logback = "1.5.22"
pdfbox = "3.0.1"
kotlinx-coroutines = "1.10.2"
slf4j = "2.0.17"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-publish = { id = "maven-publish", version = "1.0.0" }
